# numpyの関数にヴァンデルモンド行列を生成するものがあったので試してみる
- [numpy.vander¶](https://numpy.org/doc/stable/reference/generated/numpy.vander.html)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [4]:
x

array([1, 2, 3, 4, 5])

In [5]:
X = np.vander(x)

In [6]:
X

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [9]:
X = np.vander(x, increasing=True, N=3)

In [10]:
X

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

- refactorしたコードでもこの機能は使わず、内包表記での書き方としていた
- しかし、この方が簡単に書けるし間違いも少ないので、多項式回帰をする際はこの方法をとるのが良い